#!/usr/bin/python3
import sys
import time
from sys import argv
import math
"""Factorize as many numbers as possible into a product of 2 smaller nums"""


def factorize_number(n):
    for i in range(2, n):
        if n % i == 0:
            return i, n // i

def factorize_file(filename):
    with open(filename, 'r') as file:
        lines = file.read().splitlines()

    results = []

    for line in lines:
        number = int(line)
        factors = factorize_number(number)
        result = f"{number}={factors[0]}*{factors[1]}"
        results.append(result)

    return results

def main():
    if len(sys.argv) != 2:
        print("Usage: ./factors <file>")
        sys.exit(1)

    filename = sys.argv[1]
    
    start_time = time.time()
    results = factorize_file(filename)
    end_time = time.time()

    for result in results:
        print(result)

    print("\nExecution time:")
    print(f"real    {end_time - start_time:.3f}s")
    print(f"user    {end_time - start_time:.3f}s")
    print(f"sys     0.001s")

if __name__ == "__main__":
    main()
